---
- name: Demo webhook rulebook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Test connectivity by ping
      condition: event.payload.message == 'ping'
      action:
        run_job_template:
          name: Ping
          organization: Default
